### ISSUE TITLE
Foundry login screen field name changes results in failed login attempts

### ISSUE THREAD

**Issue by Norc** [felddy/foundryvtt-docker#872] opened 2024-01-06 18:22 UTC
### Bug description

Existing Docker images with saved login information are failing to log in successfully after some changes deployed to the Foundry website on Thursday. There were a few fields renamed:

`<login_redirect>` to `<next>`
`<login_username>` to `<username>`
`<login_password>` to `<password>`

To the best of my personal knowledge, the rest of the authentication workflow hasn't changed in a way that should disrupt the image.

Sorry I can't provide any detailed logs. I have not encountered the issue myself, but am just relaying information and reports that I have come accross.

### Steps to reproduce

Launch an existing, previously functional Docker image that has saved login information.

### Expected behavior

The login attempt succeeds.

### Container metadata

```shell
None available.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment] 2024-01-06 18:33
Thanks for the report.  But someone beat you to it!  

Duplicate of:
- #868 

Fix published in a release yesterday:
- https://github.com/felddy/foundryvtt-docker/releases/tag/v11.315.1

**Closed as completed by felddy** 2024-01-06 18:33 UTC
Labels: bug :bug:, duplicate :busts_in_silhouette:
