### ISSUE TITLE
License retrieval fails if more than one license is owned

### ISSUE THREAD

**Issue by VTTAssets** [felddy/foundryvtt-docker#53] opened 2020-07-20 09:54 UTC
# 🐛 Bug Report

The license key retrieval retrieves the text contents of a CSS selector

`const license_with_dashes = $("pre.license-key code").text();`

If there are multiple `pre`s, it concatenates the contents of each and writes that into the license file, resulting in an invalid license

## To Reproduce

- Buy a second license ;)
- Then run the container

## Expected behavior

Ability to specify the license key as an ARG or in the secret. I am currently looking at the code to make that happen and provide a PR if sucessful, but I have to admit that Docker is not my strong suit

**Comment by felddy** [comment] 2020-07-20 17:40
| Buy a second license ;)
🤣

**Comment by felddy** [comment] 2020-07-20 18:56
Can you confirm which of the two ways the multiple licenses are listed on the license page:

Multiple `pre` nodes, each with with `code` node:
```html
<pre class="license-key">
    <code class="hljs">AAAA-BBBB-CCCC-DDDD-EEEE-FFFF</code>
</pre>
<pre class="license-key">
    <code class="hljs">AAAA-BBBB-CCCC-DDDD-EEEE-FFFF</code>
</pre>
```

-or-

A single `pre` node with multiple `code` nodes:
```html
<pre class="license-key">
    <code class="hljs">AAAA-BBBB-CCCC-DDDD-EEEE-FFFF</code>
    <code class="hljs">AAAA-BBBB-CCCC-DDDD-EEEE-FFFF</code>
</pre>
```

I'll need this information to write the tests for CI.

**Comment by VTTAssets** [comment] 2020-07-20 19:00
It's the following:

```html
<div class="license">
  <pre class="license-key"><code>AAAA-BBBB-CCCC-DDDD-EEEE-FFFF</code></pre>

  <p><label>Purchase Date:</label> SOMEDATE </p>
  <p><label>Purchase Price:</label> SOMEPRICE</p>
  <p><label>Discount Code:</label> <code>SOMECODE</code></p>
</div>

<div class="license">
  <pre class="license-key"><code>AAAA-BBBB-CCCC-DDDD-EEEE-FFFF</code></pre>

  <p><label>Purchase Date:</label> SOMEDATE </p>
  <p><label>Purchase Price:</label> SOMEPRICE </p>
  <p><label>Discount Code:</label> <code>SOMECODE</code></p>
</div>
```

**Comment by VTTAssets** [comment] 2020-07-20 19:01
![image](https://user-images.githubusercontent.com/54429526/87975631-2c160080-cacc-11ea-9940-e390884f5577.png)

**Comment by felddy** [comment] 2020-07-20 21:25
Thank you for the quick reply.

I think I'm going to make a smaller patch to fix the bug before I merge the larger PR.   

There are a few more moving pieces in the container that will need a bit of refactoring to make your new license options more flexible.

**Comment by felddy** [comment] 2020-07-22 15:06
@VTTAssets , I've worked on the issue and incorporated some of your ideas from PR #54 into PR #55 

Could you build a test container from the `bugfix/multiple_license_keys` branch and see if the `FOUNDRY_LICENSE_KEY` environment variable works for you.  Also that setting it to `1`, or `2` selects the appropriate key from your account. 

From the `README.md`

| Name  | Purpose | Default |
|-------|---------|---------|
| FOUNDRY_LICENSE_KEY | The license key to install. e.g.; `AAAA-BBBB-CCCC-DDDD-EEEE-FFFF`  If left unset, a license key will be fetched when using account authentication.   If multiple license keys are associated with an account, one will be chosen at random.  Specific licenses can be selected by passing in an integer index.  The first license key being `1`.  May be set [using secrets](#using-secrets). | |


Build command: 
`docker build --build-arg VERSION=0.7.0 --tag felddy/foundryvtt:test https://github.com/felddy/foundryvtt-docker.git#bugfix/multiple_license_keys`

Run command:
```console
docker run \
  --env FOUNDRY_USERNAME='<your_username>' \
  --env FOUNDRY_PASSWORD='<your_password>' \
  --env FOUNDRY_LICENSE_KEY=`<license_key_or_index>` \
  --publish 30000:30000/tcp \
  --volume /data:<your_data_dir> \
  felddy/foundryvtt:test
```

***Note:*** You'll need to delete the `license.json` file between runs to get it to try to re-license. 

If everything looks good, I'll make a release for `0.6.5` and `0.7.0` with these changes.  

Thank you again for your contribution.  I really appreciate it.

**Comment by VTTAssets** [comment] 2020-07-23 13:23
I will do that, give me a moment though. I appreciate your responsiveness <3

**Comment by VTTAssets** [comment] 2020-07-25 09:38
I am getting the usage of authenticate.js:

```
Entrypoint | 2020-07-25 09:38:01 | [info] Starting felddy/foundryvtt container v0.7.0
Entrypoint | 2020-07-25 09:38:01 | [info] No Foundry Virtual Tabletop installation detected.
Entrypoint | 2020-07-25 09:38:01 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
Usage:
  authenticate.js [--log-level=LEVEL] <username> <password> <cookiejar>
  authenticate.js (-h | --help)
```

**Comment by VTTAssets** [comment] 2020-07-25 10:03
I tried it with your run command above and with a compose file (see below), but to no avail. I needed to replace the backticks in your run command for the FOUNDRY_LICENSE_FILE with regular single-quotes, and tried single, double and no quotes in the docker-compose.yml but no dice

docker-compose.yml:
```
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:test
    hostname: foundry_license_test
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: /home/sebastian/DOCKER/foundry
        target: /data
    environment:
      - FOUNDRY_PASSWORD=MYPASS
      - FOUNDRY_USERNAME=MYLOGIN
      - FOUNDRY_ADMIN_KEY=atropos
      - FOUNDRY_LICENSE_KEY=2
    ports:
      - target: "30000"
        published: "30030"
        protocol: tcp
        mode: host

```

**Comment by VTTAssets** [comment] 2020-07-25 11:07
If it helps, we can do a debugging session on my computer with my login (if we can schedule something like that. I am at GMT+1). The other option is sponsoring you a 2nd license.

**Comment by felddy** [comment] 2020-07-25 13:01
Thanks for the offer to remotely debug, and especially the 2nd license sponsorship!  I think I've resolved the issue.

I was able to reproduce the error causing the usage message from `authenticate.js`.   It occurs when verbose logging is not enabled.   (I always have `CONTAINER_VERBOSE` set to true, because... developing.)   Anyway, it was a quoting issue in `bash`, and an over zealous `shellcheck`. 

Fixed by: 3b90190404f0b7499e7e330c50827c47f4dcfa05 36251d7fc4cce24ff9b5a0db3a5666be9ec26704

If you could try rebuilding the test container and running your docker-compose again.  I have good feeling about this one.
🤞

**Comment by VTTAssets** [comment] 2020-07-26 11:06
Working fine. I didn't expect the software to detect the last test-case, but I wanted to try nevertheless. It's working great for me now, see the following test cases I went through:

```
Test: FOUNDRY_LICENSE_KEY=AAAA-BBBB-CCCC-DDDD-EEEE-FFFF (valid, first license key)
Expected Result: Use first license key
Result: Used first license key

Test: FOUNDRY_LICENSE_KEY=GGGG-HHHH-IIII-JJJJ-KKKK-LLLL (valid, second license key)
Expected Result: Use second license key
Result: Used second license key

Test: FOUNDRY_LICENSE_KEY=1
Expected Result: Use first license key
Result: Used first license key

Test: FOUNDRY_LICENSE_KEY=2
Expected Result: Use second license key
Result: Used second license key

Test: FOUNDRY_LICENSE_KEY=0
Expected Result: Invalid key, fallback to first license key
Result: Used first license key

Test: FOUNDRY_LICENSE_KEY=3
Expected Result: Invalid key, fallback to first license key
Result: Used second license key

Test: FOUNDRY_LICENSE_KEY=SOME-THIN-GELS-EYAY-WORK
Expected Result: Invalid key, fallback to first license key
Result: No license.json created
foundry_1  | FoundryVTT | 2020-07-26 11:02:43 | [warn] Invalid license key format detected, expiring license file.
foundry_1  | FoundryVTT | 2020-07-26 11:02:43 | [warn] Software license requires signature.
```

**Comment by felddy** [comment] 2020-07-26 12:14
Excellent!   Thank you for posting the results in this very readable format.   It's important to understand users' expected results.

One quick clarification.  For the last index test you listed: 

```
Test: FOUNDRY_LICENSE_KEY=2
Expected Result: Invalid key, fallback to first license key
Result: Used second license key
```

Did you mean: `Test: FOUNDRY_LICENSE_KEY=3` ?

**Comment by VTTAssets** [comment] 2020-07-26 13:43
Oh, yes, of course. Copy & Paste is the devil in disguise. Thank you!

**Comment by felddy** [comment] 2020-07-26 20:54
PR #55 has been merged.  Release [v0.6.5+a](https://github.com/felddy/foundryvtt-docker/releases/tag/v0.6.5%2Ba) and [v0.7.0+b](https://github.com/felddy/foundryvtt-docker/releases/tag/v0.7.0%2Ba) have been published to docker hub.   Thank you again for your reporting, PR, and help testing.

I hope that when the https://foundryvtt.com eventually changes and breaks the license fetcher I can ping you to test the multi-license fix.  😉

**Closed as completed by felddy** 2020-07-26 20:54 UTC
