### ISSUE TITLE
websocket error after updating to v11

### ISSUE THREAD

**Issue by orangetruth** [felddy/foundryvtt-docker#746] opened 2023-08-06 01:42 UTC
### Bug description

I'm running this on a raspberry pi with nginx. I can run v10.303 with no issues. When I update to v11 (both 11.292 or 11.306), I can access the admin screen, but when I try to launch a world, I get the error:

`WebSocket connection to 'wss://<my.domain>/socket.io/?session=97381d03648f3d1b7f1b2970&EIO=4&transport=websocket' failed: `

Any idea what may have changed to cause this? Nothing else in my config changed besides the foundry version

This is my nginx config:

    server {
    # Enter your fully qualified domain name or leave blank
    server_name             my.domain;

    # Sets the Max Upload size to 300 MB
    client_max_body_size 300M;

    # Proxy Requests to Foundry VTT
    location / {

        # Set proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # These are important to support WebSockets
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        # This should match the published port in your docker-compose file
        proxy_pass http://localhost:30004;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/my.domain-0001/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/my.domain-0001/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    }

    server {
    if ($host = my.domain) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name             my.domain;
    listen                  80;

### Steps to reproduce

- Pull a v11 foundry image felddy/foundryvtt
- try to launch a world

### Expected behavior

I expect the world to launch without websocket errors

### Container metadata

```shell
com.foundryvtt.version = "11.292"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2023-01-20T00:17:20.295Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "8343e0aa2ad277920b92caf864f2c75b08dd4661"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "11.292.0"


com.foundryvtt.version = "11.306"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2023-07-21T16:28:47.154Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "f379bf9645ef353c5a80fae0ad64866d374a2269"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "11.306.0"
```

### Relevant log output

```console
FoundryVTT | 2023-08-05 19:40:09 | [info] Software license verification succeeded
FoundryVTT | 2023-08-05 19:40:09 | [info] Server started and listening on port 30000
FoundryVTT | 2023-08-05 19:40:34 | [info] Created client session 415a8d5b54e30869747cc797
Entrypoint | 2023-08-05 19:40:45 | [debug] Timezone set to: America/Denver
Entrypoint | 2023-08-05 19:40:45 | [info] Starting felddy/foundryvtt container v11.292.0
Entrypoint | 2023-08-05 19:40:45 | [debug] CONTAINER_VERBOSE set.  Debug logging enabled.
Entrypoint | 2023-08-05 19:40:46 | [info] Foundry Virtual Tabletop 11.292 is installed.
Entrypoint | 2023-08-05 19:40:46 | [info] Not modifying existing installation license key.
Entrypoint | 2023-08-05 19:40:46 | [info] Setting data directory permissions.
Entrypoint | 2023-08-05 19:40:46 | [debug] Completed setting directory permissions.
Entrypoint | 2023-08-05 19:40:46 | [info] Starting launcher with uid:gid as foundry:foundry.
Launcher | 2023-08-05 19:40:46 | [debug] Ensuring /data/Config directory exists.
Launcher | 2023-08-05 19:40:46 | [info] Generating options.json file.
Launcher | 2023-08-05 19:40:46 | [info] Setting 'Admin Access Key'.
Launcher | 2023-08-05 19:40:46 | [info] Starting Foundry Virtual Tabletop.
FoundryVTT | 2023-08-05 19:40:50 | [info] Running on Node.js - Version 16.18.1
FoundryVTT | 2023-08-05 19:40:50 | [info] Foundry Virtual Tabletop - Version 11 Build 292
FoundryVTT | 2023-08-05 19:40:50 | [info] User Data Directory - "/data"
FoundryVTT | 2023-08-05 19:40:50 | [info] Application Options:
{
  "awsConfig": null,
  "compressStatic": false,
  "fullscreen": false,
  "hostname": null,
  "language": "en.core",
  "localHostname": null,
  "passwordSalt": null,
  "port": 30000,
  "protocol": null,
  "proxyPort": null,
  "proxySSL": false,
  "routePrefix": null,
  "sslCert": null,
  "sslKey": null,
  "updateChannel": "stable",
  "upnp": false,
  "upnpLeaseDuration": null,
  "world": null,
  "adminPassword": "••••••••••••••••",
  "serviceConfig": null
}
FoundryVTT | 2023-08-05 19:40:50 | [info] Software license verification succeeded
FoundryVTT | 2023-08-05 19:40:50 | [info] Server started and listening on port 30000
FoundryVTT | 2023-08-05 19:40:54 | [info] Created client session fdcca51bdfc08aef4d5e72ff
FoundryVTT | 2023-08-05 19:41:08 | [info] Administrator authentication successful for session fdcca51bdfc08aef4d5e72ff
FoundryVTT | 2023-08-05 19:41:16 | [info] Created client session 259800b66e558d88033e74c6
Segmentation fault (core dumped)
Launcher | 2023-08-05 19:41:22 | [error] Node process exited with code 139
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment] 2023-08-06 03:27
I believe this is a duplicate of #697.  
This issue is still open but there is a [work around](https://github.com/felddy/foundryvtt-docker/issues/697#issuecomment-1597821895).  

See:
- #697

**Closed as completed by felddy** 2023-08-06 03:27 UTC
Labels: bug :bug:, duplicate :busts_in_silhouette:

**Comment by orangetruth** [comment] 2023-08-07 22:34
I can confirm that [work around](https://github.com/felddy/foundryvtt-docker/issues/697#issuecomment-1597821895) fixed the problem for me. Thank you!
